# Generated by Django 3.2.8 on 2021-11-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название книги')),
                ('author', models.TextField(blank=True, null=True, verbose_name='Автор(-ы) книги')),
                ('genre', models.CharField(blank=True, max_length=32, null=True, verbose_name='Жанр книги')),
                ('release_year', models.IntegerField(blank=True, null=True, verbose_name='Год издания книги')),
            ],
        ),
    ]
