# Generated by Django 3.2.8 on 2021-11-11 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20211111_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-created_at',), 'verbose_name': 'Рецензия', 'verbose_name_plural': 'Рецензии'},
        ),
    ]
