# Generated by Django 3.2.8 on 2021-11-05 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(verbose_name='Рецензия на книгу')),
                ('rating', models.IntegerField(verbose_name='Оценка книги')),
                ('created_at', models.DateTimeField(verbose_name='Дата и время создания рецензии')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время обновления рецензии')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.books', verbose_name='Идентификатор книги')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='Идентификатор пользователя')),
            ],
        ),
    ]
